name: ola_uber_price_comparison
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  intl: ^0.19.0
  lottie: ^2.7.0
  sqflite: ^2.3.0
  get_storage: ^2.1.1
  permission_handler: ^11.0.1
  uuid: ^4.2.1
  geocoding: ^2.1.1
  google_maps_flutter: ^2.5.2
  geolocator: ^10.1.0
  url_launcher: ^6.2.3
  pay: ^2.0.0
  flutter_stripe: ^10.2.0
  flutter_dotenv: ^5.1.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/
    - .env
    